export enum Channels {
    GET_PAUSE_STATUS,
    SET_PAUSE_STATUS,
    CONTENT_PAGE_LOADED,
    SET_CONTENT_SCRIPT_STATUS,
    INIT_BACKGROUND_SCRIPT,
    CONTENT_MAIL_MAKE_AUTH,
    CONTENT_MAIL_UP_SPAM
};